services:
 microservicio:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8081:8080"
  environment:
   - spring.datasource.url=jdbc:oracle:thin:@j5q4b1nob2t8v68g_tp?TNS_ADMIN=/app/wallet
   - spring.datasource.username=FS_SUMATIVA2_RESERVAS
   - spring.datasource.password=Holaquetal123@
  restart: always